// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// testRapidjson
void testRapidjson(const char* json);
RcppExport SEXP _rapidjsonr_testRapidjson(SEXP jsonSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type json(jsonSEXP);
    testRapidjson(json);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rapidjsonr_testRapidjson", (DL_FUNC) &_rapidjsonr_testRapidjson, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rapidjsonr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
